### PR TITLE
Fix Punishment Bug ver 1.3

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mblokker** [comment]
Apart from some errors that you made, is this necessary? Since this has already been implemented here: https://github.com/LVPlayground/playground/blob/a52e4b23f8f51631ceed06acd222cd6ae45b0711/pawn/Resources/Callbacks/OnPlayer/OnPlayerCommandText.pwn#L410

**Comment by mrnategeek** [comment]
Really Yassine???

**Comment by ghost** [comment]
so close this issues

**Comment by ghost** [comment]
https://github.com/LVPlayground/playground/issues/218

**Comment by mblokker** [comment]
Why close that issue? Is it related to teleporting?

**Comment by mrnategeek** [comment]
What the f***?!

-MRNATE GEEK 2009-2016

**Comment by mblokker** [comment]
Do you learn MrNate? Several posts containing the same utterly useless language have been removed, please read our Code of Conduct and try to behave: https://github.com/LVPlayground/playground/blob/master/CODE_OF_CONDUCT.md

**Comment by LVPYassine** [comment]
Yes mblokker

**Comment by LVPYassine** [comment]
Why close that issue? Is it related to teleporting?

Yes

**Comment by mrnategeek** [comment]
Is this a email feature on GitHub????

-MRNATE GEEK 2009-2016

**Comment by LVPYassine** [comment]
Is this a email feature on GitHub????

Yes

**Comment by mrnategeek** [comment]
Very funny, just learning about this

-MRNATE GEEK 2009-2016

**Comment by LVPYassine** [comment]
u spam now mrnategeek  Shut up or u got a punishment in main Server

**Pull request closed without merging**
