### PR TITLE
Fix Punishment Bug With BlockCmd :D

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I Have one Think I'm not Sure on it
After Player Death and Be Spawned i think still be BlockCmd == 1
so i search on player spawn after he die to add  BlockCmd == 0

I Hope You Like it 

Waitting for u Reponse

Yassine

**Comment by RussellLVP** [comment]
It's generally a good idea to explain what the issue is that you're trying to solve— I don't quite understand. What your code does is the following:
1. Create a variable named `BlockCmd`, an array that can store a value for each player.
2. Set the `BlockCmd` value for the `lamerid` to 1. (This value is not used anywhere, so it may as well not exist.)
3. Send a message to the person who got thrown in the air in revenge for a lame kill saying their commands got blocked.

Now, unless you'd actually use `BlockCmd` anywhere, the first two of your changes are not going to do anything at all :-). Since we do block commands, there is some sense in telling the player about it, since this indeed is bound to confuse people.

Let's take a step back. Why do we block commands in the first place? Can we just remove that? (Even though @LVPDarkfire would be sad.)

**Comment by ghost** [comment]
damn !

That Gamemode Don't use any tp block or anything ? if yes tell me if no 

i suggest to replace it with ( "Kill Him !" ) or (" Spawn him ! ")

if u agree with Suggestions tell me :DD

**Comment by RussellLVP** [comment]
What do you mean with _tp block_?

The intention of throwing a player in the air is to kill them, which will respawn them. This doesn't work in all cases, notably when they're in the water and will survive the fall, which is why I suspect commands get blocked.

Do you think it's a good idea to remove blocking of commands? You can remove the `PlayerHandOfGod` variable and related code if you do.

**Comment by ghost** [comment]
so with all that we can't so something like use this on the tp cmds

example : 

> if (...................................(lamerId)) {       // .......... = idk what i write there 
>                 SendClientMessage(playerId, Color::Error, "TexT.");
>                 return false;
>             }

Add this Here : https://github.com/LVPlayground/playground/blob/master/pawn/Features/Gameplay/Teleportation/TeleportationManager.pwn

But anyhow i Suggest to Change this with another one or check old versions that bug fixed there

**Comment by ghost** [comment]
Russell I Have Another Idea u can pm me in IRC ?
i will delete This :D

**Pull request closed without merging**
