### PR TITLE
Fix Punishment Bug With Some Edit :DD

### PR DESCRIPTION
**Pull request by ghost**
Changes :

When CreateExplosion Work (DamageManager(playerId)->isPlayerFighting() == true) will be Activeted  so Player get when he try to abuse 

" Because of recent fighting activities, you aren't able to teleport. " and change 400 to 200 for he can't abuse when timer of this function stoped 

With 200 and 10 in Health ( - 2 or - 5 Explosion ) he surely Dead 

Thanks 

Yassine

### CODE REVIEW

**Comment by mblokker** [comment]
1. It's not handy to have one pull request for multiple distinct changes (lame kill punishment fix and irc message for slaps).
2. Why do we need to have the slap message on IRC echo?

**Comment by ghost** [comment]
Why do we need to have the slap message on IRC echo? : 

Removed !

**Comment by ghost** [comment]
Close this one

**Comment by mrnategeek** [comment]
I cannot be part of the scripters or staff crew, you might know why

**Pull request closed without merging**
