### PR TITLE
Improving FightClub

### PR DESCRIPTION
**Pull request by Specifer**
Solving #346 .

Thank you for making a contribution to [Las Venturas Playground](https://sa-mp.nl/)!

Please take a moment to fill in the questions in this template, to make it easier for our developers
to understand what you're doing.

## What is being changed?
Spectate Feature.

## Why is this being changed?
Improving watch and stopwatch.

### CODE REVIEW

**Review by RussellLVP — CHANGES_REQUESTED** [review]
Hi Specifer,

Thank you for the contribution. Sadly, this won't work: The `fc_player*` variables that you create are local to the `CFightClub__WatchMatch` function, so cannot be accessed anymore in other functions, in this case `CFightClub__StopWatch`.

In order to make this work, you would have to change the `aSpecInfo` variable to take three extra members: interior, virtual World and position. (As an array of X, Y and Z coordinates.) No need to store money in there, we already track that server side.

Thank you for trying to fix that issue!!

Thanks,
Russell

**Comment by Specifer** [comment]
I added that feature for players who are involved in fight too.

**Comment by Specifer** [comment]
@RussellLVP, suggest Me the lines that need work.

**Comment by RussellLVP** [comment]
> @RussellLVP, suggest Me the lines that need work.

I'm afraid most of them, this doesn't currently compile. I appreciate your contribution, but it might be easier to make a bug for this so that I can take a look later?

**Comment by Specifer** [comment]
Sure sure. I'll try to work on it, but this time better. You can close it if you want, I'll pull request later then 🤪.

**Pull request closed without merging**
