### PR TITLE
Update . rules.json

### PR DESCRIPTION
**Pull request by ghost**
[
    "{2566BA}- {A9C4E4}Do not cheat.",
    "{2566BA}- {A9C4E4}No swearing, flaming or racism.",
    "{2566BA}- {A9C4E4}Avoid CAPS; use your common sense.",
    "{2566BA}- {A9C4E4}The Ship is a peace zone; don't harm players on it and don't run to it if you're fighting!",
    "{2566BA}- {A9C4E4}Do not abuse bugs or commands.",
    "{2566BA}- {A9C4E4}Do not harm a cruise in any way!",
    "{2566BA}- {A9C4E4}Do not spam!" 
    "If you have questions, use {D67513}@<message> {A9C4E4}to contact the Las Venturas Playground staff. Have fun!"
]

### CODE REVIEW

**Comment by RussellLVP** [comment]
Sure. Not sure why these other changes are there, but I don't mind too much either.

Thank you.

**Comment by ghost** [comment]
Topic Close ! 

I so exicetted to see new rule xD
when it will be come

**Comment by RussellLVP** [comment]
We'll probably do another release this year, so a couple of days at most.

**Comment by ghost** [comment]
ok bro  ! going offline

**Pull request merged**
