### PR TITLE
Update JailCommands.pwn

### PR DESCRIPTION
**Pull request by FreakinsPL**
Thank you for making a contribution to [Las Venturas Playground](https://sa-mp.nl/)!

Please take a moment to fill in the questions in this template, to make it easier for our developers
to understand what you're doing.

## What is being changed?
JailCommands.pwn

## Why is this being changed?
Prevent jailing of NPCs

## How are you making the change?
I have tested this change myself on my local server.

### CODE REVIEW

**Review by Specifer — APPROVED** [review]

**Review by EPIC-striker — COMMENTED** [review]
INCORRECT: You can't jail a NPC
CORRECT: You can't jail an NPC

**Comment by Specifer** [comment]
Yeah, Thank you mate.

**Comment by FreakinsPL** [comment]
Done :)

**Review by RussellLVP — APPROVED** [review]
Thank you!

**Pull request merged**
