### PR TITLE
Improving /credits

### PR DESCRIPTION
**Pull request by Specifer**
Implementing Issue #746

Need your opinion on these mates.

### CODE REVIEW

**Comment by BeanerLVP** [comment]
Holsje's name is missing from the developers' list.

**Comment by Specifer** [comment]
Tysm. I wanted to add it though! Sorry @OttoRocket-LVP :(.

**Comment by RussellLVP** [comment]
Could you share a screenshot what this looks like? I think it's great, probably want to think about updating them wholesale.

**Comment by Specifer** [comment]
ok

**Comment by Specifer** [comment]
Screenshot (205)

**Comment by XilentLVP** [comment]
Looks nice! Good job! :)
I suggest to modify striker's nickname from 'Striker' to 'striker'.

**Comment by Specifer** [comment]
> 
> 
> Looks nice! Good job! :)
> I suggest to modify striker's nickname from 'Striker' to 'striker'.

Done ;)  .

**Review by RussellLVP — APPROVED** [review]
Thank you!

**Pull request merged**
