### PR TITLE
Improve freeze and avoid abuse

### PR DESCRIPTION
**Pull request by Specifer**
Solving and Implementing for Issue #777.

### CODE REVIEW

**Comment by Specifer** [comment]
Reverted as per Striker and Beaner's view

**Comment by RussellLVP** [comment]
This does not compile, and freezes players the moment they execute _any_ command until they're fixed - which then freezes the person fixing them.

**Comment by Specifer** [comment]
It seems I have left brackets but after doing so, everything is working fine for me.

**Comment by Specifer** [comment]
I need a hint on solving this. Would making a variable of this and using if condition work. Btw why does this freeze player on any command, this must be brought to notice only when the player is frozen right. why is this working another way around?

**Comment by RussellLVP** [comment]
If I'm honest, there's no good way of fixing this right now because we don't track whether a player is frozen. The commands would have to move to JavaScript wholesale.

**Comment by Specifer** [comment]
So perhaps closing this PR for now is best?

**Comment by RussellLVP** [comment]
Yes, I think we should.

**Pull request closed without merging**
