### PR TITLE
Addition of new locations tow-part-3

### PR DESCRIPTION
**Pull request by Specifer**
#631

### CODE REVIEW

**Comment by Specifer** [comment]
Idk why when I do /tow 19, I go there. But when I do /tow. Only up to "Bayside M" is showing, Where it is Bayside Marina .

**Comment by OttoRocket-LVP** [comment]
> Idk why when I do /tow 19, I go there. But when I do /tow. Only up to "Bayside M" is showing, Where it is Bayside Marina .

https://github.com/LVPlayground/playground/blob/fe3353045b4a20fab7e78bce258ce4cd0ede0976/pawn/Elements/Player/Tow.pwn#L136 formats the locations.

https://wiki.sa-mp.com/wiki/Format shows that second param is max length.
Size of https://github.com/LVPlayground/playground/blob/fe3353045b4a20fab7e78bce258ce4cd0ede0976/pawn/Elements/Player/Tow.pwn#L134 initializes it to a size of 256

**Comment by OttoRocket-LVP** [comment]
Also,

I'm not sure why we need so many tow locations? Won't it start to get confusing having so many?

Wouldn't we need an easier menu to choose where to tow to. And do we think those (new) locations will get used?

**Comment by Specifer** [comment]
Ty Holsje, from my point of view. Adding more locations would lead players to spread out on all cities pretty quickly, for example bayside marina. There are a lot of houses free and still, players don't know there are houses there. And tries to find a house across LV. And by new locations, I'm sure we can see the distribution of players across cities. 
Edit: It is shown now !!! Thank you Holsje.

**Pull request closed without merging**
