### PR TITLE
Update AdministratorCommands.pwn

### PR DESCRIPTION
**Pull request by ghost**
I Donot know its right or not
 but Putting my Aim Anywhere

### CODE REVIEW

**Comment by jadegraaf** [comment]
What are you trying to achieve? Please be more descriptive in your pull request.

**Comment by debuggest3** [comment]
This pull request will cause compile errors. Therefore we cannot accept it in the way it is now.

We'd like you to do two things:
1. Explain what you are trying to change and why.
2. Fix the pull request so that the code can be compiled and actually works when run as a SA-MP gamemode.

**Comment by ghost** [comment]
I want to Fix this https://github.com/LVPlayground/playground/issues/80

**Comment by debuggest3** [comment]
I'm sorry, you clearly have no idea what you are doing. I suggest learning how to program in Pawn before making any more pull requests. Thank you.

**Pull request closed without merging**
