### PR TITLE
Updated SLAP_REASONS.

### PR DESCRIPTION
**Pull request by winniemolbilus**

### CODE REVIEW

**Review by HopperLVP — COMMENTED** [review]
Did you talk with the  developer team about this changes..  ?

**Comment by winniemolbilus** [comment]
well, george told me that it's fine to add and ye it's okay... developer will pass it

**Comment by xhoogland** [comment]
Although it certainly is an idea to expand the slap-reasons, I would love to see a more generic one than a certain player. ;)

**Comment by RussellLVP** [comment]
Why not :) Let's merge this, thank you!

**Pull request merged**
