### PR TITLE
No Tax for admins

### PR DESCRIPTION
**Pull request by GodeyLVP**
Correct me if i'm wrong.
This idea was given by GrannyLVP along with free nos.

-Godey

### CODE REVIEW

**Comment by mblokker** [comment]
It would be more common to use https://github.com/GodeyLVP/playground/blob/patch-12/pawn/Entities/Financial/TaxAgency.pwn#L79 for that. That if-statement checks specifically if a player is egligable for tax collection. So, if admins are to be exempt from that, add a rule for that here: https://github.com/GodeyLVP/playground/blob/patch-12/pawn/Entities/Financial/TaxAgency.pwn#L52

**Comment by GodeyLVP** [comment]
Can you just add it yourself please? 'Cause it's just a matter of changing the rules, from the addition I made.
I don't want to make a spam of pull requests that's all
Thanks!

-Godey

**Comment by mblokker** [comment]
You can spam pull requests all you want, we always appreciate your work!

**Comment by RussellLVP** [comment]
Certainly, but please do learn how to update code in a pull request - there is no need to create a new one every time :)

**Comment by mblokker** [comment]
Right now you're returning 'true' when a player has an admin status. If you look at the function name, it says 'isPlayerEligableForTaxCollection()'. When you 'return true', you're making this admin player eligible for tax collection, which is the opposite of what we want.

**Comment by ghost** [comment]
This PR has been sitting here with no updates for quite some time, what do we want to do?

**Comment by ghost** [comment]
https://github.com/LVPlayground/playground/issues/92

**Pull request closed without merging**
