### PR TITLE
Added /PL [player] for Packet Loss checking.

### PR DESCRIPTION
**Pull request by Starboy-Xo**
Added a command: /PL [player] for Packet Loss checking. Below /HS Hit Sound command

### CODE REVIEW

**Comment by HolsjeLVP** [comment]
You should put /PL into the player commands instead of "AdministratorCommands".
Also, would be neat to fix /HS while you're at it.

However, for the command to work you'll have to add it to the OnPlayerCommandText:
https://github.com/LVPlayground/playground/blob/6392a010a2fe46ad46070440f15eb21ade7c9b79/pawn/Resources/Callbacks/OnPlayer/OnPlayerCommandText.pwn#L581
^That's where HS is at.

Also, why are you using the information color for own PL, and succes color for other people's PL, does this have a reason?

**Comment by Starboy-Xo** [comment]
> You should put /PL into the player commands instead of "AdministratorCommands".

I am sorry i was just following the /HS command.

> However, for the command to work you'll have to add it to the OnPlayerCommandText:

Thank you: I added the command in OnPlayerCommandText.pwn

> Also, why are you using the information color for own PL, and succes color for other people's PL, does this have a reason?

/PL [player] 
If you gave no params, it was supposed to send message like 'Please Use: /PL [player]'
But i modified it, Made it like you dont need to check your own ID to put it in, but just type in /PL and press Enter and voila get your own packet loss info right away, and if you are willing to watch other's it extends the information by saying . To check other's, Use: /PL [player].

Colors: Embeded colors were put there just to depict and differentiate that it's player's own PL and Target's PL. 
Putting in those
> Color::Success
> Color::Information

Were just to follow the other commands order. That is why i just had not put them, otherwise there are variety of hexadecimal color values. Even -1 is also an internally defined hexadecimal value '0xFFFFFFFF'.

Thank you!

**Comment by HolsjeLVP** [comment]
Sorry, didn't pay enough attention to notice you had overwritten the color values inside the actual text.
You should try to use LVP's standard coloring though (Using the actual color::) so that different commands won't be having different color feedback.

I still think it would be wise to move this away from Admincommands, I know /hs is there, but it just shouldn't be either

**Comment by xhoogland** [comment]
For the reasons of this function not being reliable, see http://wiki.sa-mp.com/wiki/NetStats_PacketLossPercent, we have decided to remove it from our code on several places.

Why would you like to see such a command?

**Comment by Starboy-Xo** [comment]
It atleast gives a rough idea of the packetloss in the ping of a player. Which atleast tells us whether player is fit for deathmatching or not.
There is another method of detecting the packet los

The method is:

`Float:GetPlayerPacketloss(playerid){
	if (!IsPlayerConnected(playerid)){
		return 0.0;
	}

	new plstr[500];

	GetPlayerNetworkStats(playerid, plstr, sizeof(plstr));

	new start = strfind(plstr, "Packetloss", false);

	strmid(plstr, plstr, start + 12, strfind(plstr, "Messages", false, start) - 2);

	return floatstr(plstr);
}
`

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

@xhoogland did a good job at explaining our position on this.

**Pull request closed without merging**
