### PR TITLE
Error message of /v save

### PR DESCRIPTION
**Pull request by FreakinsPL**
Thank you for making a contribution to [Las Venturas Playground](https://sa-mp.nl/)!

Please take a moment to fill in the questions in this template, to make it easier for our developers
to understand what you're doing.

## What is being changed?
Error message of /v save

## Why is this being changed?
Important

## How are you making the change?
 I have tested this change myself on my local server.

### CODE REVIEW

**Comment by Specifer** [comment]
No freakins, This is wrong. This message is displayed when selection is out of context. You need to create a new condition in the required file and create a new message like this.

**Comment by RussellLVP** [comment]
You're both close :)

This message triggers when trying to save a vehicle, and neither of the following conditions are true:

  1. The player is an administrator, ("Save to vehicle layout.")
  1. The player has a house with a parking lot. ("Save as a house vehicle.")

The VIP right mention is something I had intended to implement, but didn't.

I think that simplifying to something like the following would make a lot of sense:

```
@error You need to have a house with a parking lot in order to save this vehicle.
```

**Comment by FreakinsPL** [comment]
Ok :)

**Comment by RussellLVP** [comment]
Ace, thank you!

**Pull request merged**
