### PR TITLE
Fixed version of nos (1)

### PR DESCRIPTION
**Pull request by GodeyLVP**
Cleared Old bugs mentioned by Russell
Fix bugs please!
[REF: https://github.com/LVPlayground/playground/pull/116]

-Godey

### CODE REVIEW

**Comment by mblokker** [comment]
By doing `return 1` prematurely, the player won't hear the sound and not see the message done at the end of the comand: https://github.com/GodeyLVP/playground/blob/patch-10/pawn/Features/Gameplay/Vehicles/NitroHandler.pwn#L115

Also, for more cleanliness you could do `Player(playerId)->isAdministrator() == true`

**Comment by xhoogland** [comment]
Small thingie that catched my eye is that we now have double AddVehicleComponent for each case. It would be nice to not have that. :+

**Comment by ghost** [comment]
This PR has been sitting here with no updates for quite some time, what do we want to do?

**Comment by ghost** [comment]
https://github.com/LVPlayground/playground/issues/92

**Pull request closed without merging**
