### PR TITLE
Relieve Admin powers from normal tp

### PR DESCRIPTION
**Pull request by Specifer**
Solving issue #792.

### CODE REVIEW

**Review by RussellLVP — APPROVED** [review]
This is going to make my life a nightmare, but sure, let's do it, I agree with the idea.

**Comment by EPIC-striker** [comment]
Well, exclude Managers since the problem is caused by the Administrators and not us lol

**Comment by Specifer** [comment]
Yep

**Comment by BeanerLVP** [comment]
Instead of disabling it altogether and forcing administrators to use /stp (which doesn't display any chat message to the target), how about displaying a warning/confirmation message in the chat and requiring the administrator to use /tp <target> twice, if they used /tp recently (< 3 minutes)? We used to (or still do?) have this feature for VIPs whose teleports are disabled.

**Comment by FreakinsPL** [comment]
Getting error : **"You may only carteleport once every 5 minutes"**  in /stp

@Specifer @RussellLVP

**Pull request merged**
