### PR TITLE
For Improving /vip.

### PR DESCRIPTION
**Pull request by Specifer**
Implementing /VIP in JSON solving issue #707.

Thank you for making a contribution to [Las Venturas Playground](https://sa-mp.nl/)!

Please take a moment to fill in the questions in this template, to make it easier for our developers
to understand what you're doing.

## What is being changed?
/VIP in js

## Why is this being changed?
For improvement of details.

## How are you making the change?
  [Done] I have a working check-out of Las Venturas Playground.
  [Done] I have included tests for any changed JavaScript code.
  [Done] I have tested this change myself on my local server.

### CODE REVIEW

**Comment by RussellLVP** [comment]
Thanks Specifer! This looks good.

@XilentLVP would you be able to give this a look-over?

Thanks,
Russell

**Comment by XilentLVP** [comment]
Sure @RussellLVP!
Good work @Specifer, but I'm thinking about changing text colors. Let's use a little lighter colors for this.
{B4CCE8} - this for texts and titles.
{FF8E02} - this for features. (description) and same for 'Las Venturas Playground' and 'https://sa-mp.nl/donate'
Something as https://github.com/XilentLVP/playground/commit/fda6b5654961a86b5656078fd1c00ce5634157af
Thank you!

**Comment by EPIC-striker** [comment]
> Sure @RussellLVP!
> Good work @Specifer, but I'm thinking about changing text colors. Let's use a little lighter colors for this.
> {B4CCE8} - this for texts and titles.
> {FF8E02} - this for features. (description) and same for 'Las Venturas Playground' and 'https://sa-mp.nl/donate'
> Something as [XilentLVP@fda6b56](https://github.com/XilentLVP/playground/commit/fda6b5654961a86b5656078fd1c00ce5634157af)
> Thank you!

Maintain a color structure, I agree.

**Comment by Specifer** [comment]
Done! Sorry I always look forward to using different colors.

**Comment by Specifer** [comment]
@RussellLVP, Is something wrong?

**Comment by RussellLVP** [comment]
No, thank you. Merged! :)

**Pull request merged**
