### PR TITLE
Spawn Protection

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/LVPlayground/playground/issues/425

### CODE REVIEW

**Comment by LVPYassine** [comment]
merge this ! :/

**Comment by debuggest3** [comment]
The build bot is failing with some JavaScript checks. Unfortunately, we cannot accept any pull requests with failing checks. Please fix the issue, and someone will eventually get around to looking over your code.

Note that we're all volunteers here with only limited amount of time. Especially this time of year most people have other responsibilities. Please be patient. Thank you.

**Comment by ghost** [comment]
Java Scipt tests is a normally because java structure is changed and the json complier isn't updated :P 

you can see the recents PR Megred https://github.com/LVPlayground/playground/pull/426 https://github.com/LVPlayground/playground/pull/249

+

i just edited pwn script not json files

**Comment by LVPYassine** [comment]
bump

**Comment by ghost** [comment]
To put it bluntly, this PR is a disaster. That's why it hasn't been merged yet. 

Stop bumping this and be patient.

**Comment by LVPYassine** [comment]
> this PR is a disaster.

k.

**Comment by ghost** [comment]
https://forum.sa-mp.nl/thread-33660.html

@RussellLVP

**Comment by ghost** [comment]
Well.

**Pull request closed without merging**
