### PR TITLE
Update rules.json

### PR DESCRIPTION
**Pull request by FreakinsPL**
Thank you for making a contribution to [Las Venturas Playground](https://sa-mp.nl/)!

Please take a moment to fill in the questions in this template, to make it easier for our developers
to understand what you're doing.

## What is being changed?
 Updating /rules; adding a line "Advertising is NOT ALLOWED"

## Why is this being changed?
 Necessary 

## How are you making the change?

 I have tested this change myself on my local server.

### CODE REVIEW

**Comment by FreakinsPL** [comment]
Shall we remove "DO NOT avoid death by means of quitting" line from /rules ??
@Russell

**Comment by XilentLVP** [comment]
I suggest keeping the same message - '**_DO NOT_**' @FreakinsPL 
What about a little change in '**_DO NOT advertise_**'?

**Comment by FreakinsPL** [comment]
I will update it soon From "Advertising **NOT ALLOWED**" to "**DO NOT** Advertise 
😄

Btw I am confused in that "quit to avoid death" rule coz it will now grants kill to the player according to **LVP 50 update** 😓

@XilentLVP @Specifer

**Comment by Specifer** [comment]
I'm afraid it's for the managers to exactly determine this rules.json. A minor mistake in this could have players mentioning as there is no rule about what they did.

**Comment by RussellLVP** [comment]
Could you have a look at the changed files please? Only a teeny tiny subset is relevant to this PR, you might have to rebase and update.

https://github.com/LVPlayground/playground/pull/789/files

**Comment by FreakinsPL** [comment]
Sorry for this mess
I will update it soon..

**Comment by Specifer** [comment]
@FreakinsPL , I see you have deleted you're repo to refork. So now onwards for every PR you make. you should create a new branch. and I learned this by closing so many PR's again and again.

**Comment by Specifer** [comment]
Closed by request of @FreakinsPL .

**Pull request closed without merging**
