### PR TITLE
Fixing Tow 12 bug with Delete (=) for be %d > (12)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RussellLVP** [comment]
`towLocations` is an array with exactly 12 entries. Array indices are zero-based, so the valid values are [0...11]. This code is correct right now; with your change, we'd access an entry in the array that does not exist, which could crash the gamemode.

Generally it's easier to describe what the problem is, and how it can be reproduced. In this case, there are two ways how you can end up in this code:
1. Using the dialog when typing `/tow`.
2. Using the `/tow` command with a number: `/tow 12`.

In the second case, we'd bail out on line 115 or Tow.pwn.

Looking at the code, there's no such thing as `/tow 12`. I recall that @xhoogland did a thing with the balloon that had Id 12, maybe he knows more?

**Comment by ghost** [comment]
Hello Russell !!

I see in the gamemode : 

> #define         NumberOfTowLocations    12

and 

> new Float:towLocations[NumberOfTowLocations][] =
> {
>     //   X              Y              Z              Ang
>     {2040.3169,     1543.9515,      10.3989,        359.8656}, // The Ship
>     {2275.3425,     2452.5320,      10.5474,        90.2915}, // Police Station
>     {1608.8065,     1620.8003,      10.5474,        178.2039}, // LV Airport
>     {-2329.8596,    -1602.7991,     483.4960,       215.9221}, // Mt. Chilliad
>     {2532.9568,     2071.4619,      10.4708,        0.1174}, // Ammunation
>     {340.6580,      1905.6421,      17.3677,        83.2379}, // Area 69
>     {381.2291,      2539.5469,      16.2661,        173.0934}, // Airstrip
>     {1573.1437,     -1308.5918,     16.9955,        269.2577}, // Los Santos Basejumping
>     {-1341.4988,    -248.8117,      13.8755,        342.4696}, // SF Airport
>     {1890.2701,     -2627.1948,     13.2740,        0.2716}, // LS Airport
>     {2422.0320,     1113.8469,      10.4708,        0.3177}, // LV Main bank
>     {2765.3484,     1281.4395,      10.4771,        269.4123} // LV Train Station
> };

and i noticed when Player use /tow 12 He Get : 

> You entered an invalid location ID!

and i think the problem is here  if(location < 0 || location >= NumberOfTowLocations)

Because if "%d >or = NumberOfTowLocations" with " NumberOfTowLocations    12"

so %d >= 12
if u looks up u see  Tow 12 = LV Train Station
so it's not work 

Thanks 

Yassine

**Comment by jadegraaf** [comment]
@LVPYassine, like Russell explained, arrays start at 0. /tow also starts at 0.

/tow 0 will take you to the first location which is stored in towLocations[**0**].
/tow 1 will take you to towLocations[1]
...
/tow 11 will take you to towLocations[11], 11 being the index for the 12th and last item in the array.

This means their cannot be a /tow 12 since there are only 12 locations defined, /tow 12 would required 13 locations.

I hope this explains it

**Comment by ghost** [comment]
Dear's oostcoast and Russell ,

I'm sure of this fix Please u can test this edit in BETA Server and we will test it tomorrow in 12:00 GMT + 0

Notice : if Numberoflocations = 12
and %d >= Numberoflucations
so it %d >= 12
so %d = { 12. 13 . 14 .....} tow 12 never work
but if %d > 12 
it's %d = { 13 . 14 . 15 ...}

i repeat Please Test it in BETA server i will join it tomorrow in 12:00 GMT + 0

Thanks,

Yassine

**Comment by ghost** [comment]
other Notice : i want fix that without change numberoflocations

**Comment by xhoogland** [comment]
Let me explain this on a bit more easier level (I hope).

> new Float:towLocations[NumberOfTowLocations][] { //blabla }

That line gives us 12, since that is what NumberOfTowLocations is, possible floats to push in the array. Pawn, and (almost?) every other programming language starts at 0 with numbering, which is the 1th value! If you count further to the 12th value, you will find out that the nr in the array will be 11. Towing to nr 11 in the array, means that you will be towed to the 12th location.

This means that the code of ">= NumberOfTowLocations" is correct. Removing the = in that equation would cause an error, overflow or whatever in the code/in-game since there is NO nr 12 in the array..

**Comment by ghost** [comment]
If i change the locations number to 13 that will give us some erreurs in pawn compilation so  Please and its repeut test it in the BETA  Server i will join it tomorrow in 12:00 
Or tell me how i can run it in my home to test it :D

**Comment by xhoogland** [comment]
> new Float:towLocations[NumberOfTowLocations][] =
> {
>     //   X              Y              Z              Ang
>     {2040.3169,     1543.9515,      10.3989,        359.8656}, // The Ship
>     {2275.3425,     2452.5320,      10.5474,        90.2915}, // Police Station
>     {1608.8065,     1620.8003,      10.5474,        178.2039}, // LV Airport
>     {-2329.8596,    -1602.7991,     483.4960,       215.9221}, // Mt. Chilliad
>     {2532.9568,     2071.4619,      10.4708,        0.1174}, // Ammunation
>     {340.6580,      1905.6421,      17.3677,        83.2379}, // Area 69
>     {381.2291,      2539.5469,      16.2661,        173.0934}, // Airstrip
>     {1573.1437,     -1308.5918,     16.9955,        269.2577}, // Los Santos Basejumping
>     {-1341.4988,    -248.8117,      13.8755,        342.4696}, // SF Airport
>     {1890.2701,     -2627.1948,     13.2740,        0.2716}, // LS Airport
>     {2422.0320,     1113.8469,      10.4708,        0.3177}, // LV Main bank
>     {2765.3484,     1281.4395,      10.4771,        269.4123} // LV Train Station
> };

_How many lines are between the line 3 and line 16?_ **12**
_How many taxi locations are there according to the define NumberOfTowLocations?_ **12**
_Are values from 0 to 11 (including 0 and 11 themselves) valid values for /tow?_ **Yes.** _How many are those?_ **12**
_Does "locationid < 0" allow 0 (the 1st value)?_ **Yes** _Does "locationid >= NumberOfTowLocations" allow 11 (the 12th value)?_ **Yes** _Does it allow 12 (the 13th value, which is not represented in the array either)?_ **No, since there is none.**

Hence you are getting compile errors in compiling. Please ask these question to yourself and look again in the code if your answer is different.

**Comment by ghost** [comment]
And its mean x > NumberOfTowLocations  not locations < 0

**Comment by xhoogland** [comment]
Please see my last added line.

**Comment by RussellLVP** [comment]
I confirmed that `/tow 11` teleports me to the train station in Las Venturas, which is what this issue assumes to be `/tow 12`. As such, I'm closing the pull request because this is not a bug.

Yassine, thank you for contributing to Las Venturas Playground! The issue you're trying to solve here is not a bug because the 12 tow locations range from zero to eleven: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], as opposed to a more natural one to twelve range.

**Pull request closed without merging**
