### PR TITLE
For !help communication_commands.test.js

### PR DESCRIPTION
**Pull request by Specifer**
with #576

### CODE REVIEW

**Comment by RussellLVP** [comment]
The tests fail. Have you run them?

Before proceeding, I think it's important that you get the tests up-and-running. They're a really important part in making sure that our code doesn't contain avoidable bugs, and actually does what it's supposed to do.

You can check out the staging server here:
https://github.com/LVPlayground/server-staging

Be sure to use something like the GitHub for desktop client if you're not proficient with git, as it depends on git-lfs which is not entirely straightforward.

**Comment by Specifer** [comment]
its showing (mysql error : unable to connect) , i just copy pasted the database.json content and still .

**Comment by RussellLVP** [comment]
Hi @Specifer, I have updated the updated the contribution guide to make this easier:
https://github.com/LVPlayground/playground/blob/master/CONTRIBUTE.md

Please follow it, and send me a PM on the forums so that I can share the right `database.json` file with you.

**Comment by Specifer** [comment]
Thank you very much .

**Pull request closed without merging**
